spring.application.name=talent-search-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/talentsearchdb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090